baseurl = "http://www.example.com"
title = "eduardoaleixo"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"
disableLanguages = ["es"]

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "eduardo aleixo"
  info = "self-reliant fullstack dev"
  description = "eduardo aleixo's personal website"
  keywords="developer,personal"
  since = 2020

  custom_scss = ["scss/custom.scss"]
[languages]
    [languages.en]
	languagename = "english"
	flag="ðŸ‡ºðŸ‡¸"

        [languages.en.params]
	   languageLink = "english version"

        [languages.en.menu]

           [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

    [languages.pt-br]
    	languagename = "portuguÃªs"
	flag="ðŸ‡§ðŸ‡·"

        [languages.pt-br.params]
	    info = "fullstack dev auto-suficiente"
            description = "site pessoal de eduardo aleixo"
	    keywords="desenvolvedor,pessoal"
	    languageLink = "versÃ£o em portuguÃªs"

        [languages.pt-br.menu]
            [[languages.pt-br.menu.main]]
            name = "Sobre"
            weight = 1
            url = "about/"

            [[languages.pt-br.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

#    [languages.es]
#        languagename = "espaÃ±ol"
#
#        [languages.es.params]
#	    info = "fullstack dev autosuficiente"
#            description = "sitio personal de eduardo aleixo"
#	    keywords="desarrollador,personal"
#
#        [languages.es.menu]
#            [[languages.es.menu.main]]
#            name = "sobre mi"
#            weight = 1
#            url = "about/"
#
#            [[languages.es.menu.main]]
#            name = "blog"
#            weight = 2
#            url = "posts/"
